### ISSUE TITLE
Order of variables

### ISSUE THREAD

**Issue by zstars** [weblabdeusto/Boole-Web#11]
Copied as is from Zubia:

"
3. El tema del orden de las variables creo que tiene que ver con el orden distinto en varuos sitios, habría que mirarlo. Y esto es importante.
La asignación correcta es
a. La primera variable de la tabla de verdad (empezando por la izquierda) se corresponde con la barra central de la parte superior (horizontal), 
b. La segunda variable de la tabla de verdad se corresponde con la barra central vertical .
c. La tercera variable de la tabla de verdad se corresponde con la barra horizontal a la derecha del todo.
d. La cuarta variable de la tabla de verdad se corresponde con la barra vertical abajo del todo.

No hay que cambiar los 0 y los 1, están bien asignados. Solo hay que cambiar las letras en sius posiciones para que sean coherentes la tabla de verdad con el VK (distinta representación de la misma cosa)
"

**Comment by cruzeneko** [comment]
Whoops! Solved!
