### ISSUE TITLE
reinciiar en el circuito no hace nada

### ISSUE THREAD

**Issue by garciazubia** [weblabdeusto/Boole-Web#20]
pues eso

**Comment by cruzeneko** [comment]
Esto solo se puede observar en el despliegue. Está corregido en las últimas versiones (incluyendo mi versión local). @zstars estás seguro de que el despliegue está actualizado desde weblabdeusto/Boole-Web?

**Comment by cruzeneko** [comment]
Esto ya está actualizado en el despliegue.
