### ISSUE TITLE
Other "canonic form" styles

### ISSUE THREAD

**Issue by zstars** [weblabdeusto/Boole-Web#6]
Requested by Zubia, copy-pasted as is:
"Falta sacar las formas canónicas en forma sumatoria (y también como producto de máxitérminos y en modo productorio). No es crítico por ahora."

**Comment by cruzeneko** [comment]
The formulae supported now are the following:

- Sum of product terms (sum of minterms) 

- Product of sum terms (product of maxterms) 

- Sum of product terms in summation form 

- Product of sum terms in product form

**Comment by cruzeneko** [comment]
I'm closing this because I think what is done is sufficient. Feel free to reopen if not.
